### ISSUE TITLE
Otimização na configuração/preparação

### ISSUE THREAD

**Issue by brnrdog** [coopera/teamtracker#26]
Tem sido complicado configurar e preparar o projeto. 
Por exemplo, eu setei as variáveis de ambiente, liberei acesso no meu github, e ainda assim, quando acesso `listeners/github/new`, ele me diz que não pode acessar `organizations` da minha conta. Apesar de ter garantido todas as permissões. Aliás, eu nem tenho certeza que estou logado. Eu preciso ficar debugando o `session[:user]` para poder verificar se estou logado, isto é muito chato e nada produtivo.

Também não estou achando muito adequado alimentar o banco através dos `controllers` (listeners). Não seria melhor separarmos essa lógica em classes de serviço? Faz muito mais sentido para mim, e fica mais claro.

Vamos discutir isso, por favor.

**Comment by IgorMarques** [comment]
O ideal seria marcar um hangout ou algo assim pra todo mundo ficar a par de tudo.

**Comment by brnrdog** [comment]
Concordo, @IgorMarques

**Comment by IgorMarques** [comment]
Posso todos os dias a partir das 21h horário do brasil.

**Comment by brnrdog** [comment]
A priori, posso todos os dias a partir das 20h

**Comment by IgorMarques** [comment]
@lucasbibiano e aí, pode quando?

**Comment by IgorMarques** [comment]
Rodar o sistema agora vai ser com base num dump do banco. Procedimento descrito no grupo #teamtracker do nosso Slack
